package com.rockofmam.OdoScan.enums;

public enum Brand {
    TOGG, FORD, BMW, MERCEDES_BENZ, JEEP, AUDI, TOYOTA, ALFA_ROMEO, HONDA, TESLA, PORSCHE, FIAT, JAGUAR, VOLKSWAGEN,
    HYUNDAI, NISSAN, CHEVROLET, LAMBORGHINI, FERRARI, SUBARU, MAZDA, VOLVO, KIA, PEUGEOT, MITSUBISHI, SUZUKI, CITROEN,
    RENAULT, SKODA, OPEL, ISUZU, DACIA
}
